/**
 * AUTO-GENERATED by scripts/process-images.mjs — do not edit by hand.
 * Maps public image paths to intrinsic size + blur placeholder.
 */
export interface GeneratedImage {
  width: number;
  height: number;
  blurDataURL: string;
}

export const generatedImages: Record<string, GeneratedImage> = {
  "/images/combos/bhetki-fish-fry-combo.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoQABQAPxFysFAsJqSisAgBgCIJbADCgCKSp++PazQXc7QAAP7lmUUYumhftMkjdPCGrO6T1dzAfZRMXX/kV7DO1GIB/BlRhtsdJnkXIMmTGJUqGZf97AkrB+Iy6QHCfjl0pppblGAAAA=="
  },
  "/images/combos/burger-combo.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwBACdASoQABQAPxFwsFAsJiSisAgBgCIJYgC7IDZDAbAY0j3TYrOWC4AA/ulYVVVHALsmY+p1LYfYpxvv3GmaCQw60Ln9GStjxtIoI8fq/dGsubgSCStkNbVw5zgOwaTDY2YmgigAAA=="
  },
  "/images/combos/crispy-chicken-combo.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoQABQAPxFysFAsJqSisAgBgCIJZAAAXlUZh+Zi9wYJhWkAAP7jZ4p8cr6V20FoMPYJPYxzcIHC6BSBiEFlscGRMy/TLImh/ASgGwU8yFXMzAQmmq9irSAA"
  },
  "/images/combos/signature-meal-box.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACwAwCdASoQABQAPxFysFAsJqSisAgBgCIJaACw7B9bCoKfXYXeUAD+GBLnDr4O+KlkSsqeE4zr1iMq7qyXiW2qwsLXenqzwBUocUSLpLlnl3VMonO2MtSD6UDxnVlAaVLTxHNe2FlBC7Ydfz307fk4rZQGpUAd+XNkfo2MxGq6UAAA"
  },
  "/images/dishes/belgian-coffee.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACQAwCdASoQABQAPxFwsFAsJiSisAgBgCIJQBadAfpouRY8Fs0oAP7mYCEFQRB8Gfrc6p3nyhxhR/jJ7ENHawKflvV8bcGD2vN8zhXxNnLXwuNbuVJVReeB2HQGgSxUh72IeoIHvW6s5+QAAAA="
  },
  "/images/dishes/bhetki-fish-fry.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAwBACdASoQABQAPxFysFAsJqSisAgBgCIJQBOmUABf4XeoWyiBIgC96qAA/un3jDp9aAaVoBfuVWtJcypNLe2wglO/OeKecgM5jr/xKZ4QxugePnYTJiql3RRIJGUpx3Hf/X1Mq70XjeAnj/gt9fVgAAA="
  },
  "/images/dishes/cheese-chicken-bombs.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQBACdASoQABQAPxFysFAsJqSisAgBgCIJbAC06CHfcDD/TQ3apRqRJAD+6+udOSJ40ZPKP3lXNmoDv+TtMKIDUZpEazy/a/rfCxUxwmrQaoyh/cx1NMGr41fzPHOOgVgAAA=="
  },
  "/images/dishes/chips-chaat.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBACdASoQABQAPxFysFAsJqSisAgBgCIJaAC7AB6+1pDgwyx9jv/siraAAP67LvXxZ9zaoWUPGskc/0vzbdTuKemy8EqqbaauLqxmxB5jt3hLZlL4vJYrcOjoTd9yXBv4WzfJZGnEmZJ2rfi2SAaQAAA="
  },
  "/images/dishes/crispy-chicken-pizza.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwAwCdASoQABQAPxFysFAsJqSisAgBgCIJbACdACP7jUQYIeD3AcIAAP7ZpUXZID7kuC6au5vTKYVpjFRarDSoxqjo+/6ATbupqnnBGVUOlM9GQazIMODEIcO72CtsW+MLtlqkQZIRkAbT4OzOwrQrsm0jKOOUZWWVa5AAAAA="
  },
  "/images/dishes/french-fries.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoQABQAPxFysFAsJqSisAgBgCIJbACdAB4/+RMnzHzujk7wAP7mZ9xkSXcm35pzSxzakvjRbhC7b0E69GYETcI4hiMa4+tQQ0HZyHeJP0qzq8I+YP0aS4ylxuIllfBOWWqntJNhc6ol7JQhwAA="
  },
  "/images/dishes/fried-momo.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQAwCdASoQABQAPxFysFAsJqSisAgBgCIJbACdMoACtVz5TxwCdgAA/untAkyGfD8pVADrdsKiHGTOmagYlTP5QiUxsaIrp9U9TYLNmURhZoVjC1Yuueuehi5GdzsBkvg815wjVqRvuQiw4rBULsjKkTGLknHesIAAAA=="
  },
  "/images/dishes/maggi.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwAwCdASoQABQAPxFysFAsJqSisAgBgCIJQBb3A83zjcwRCbdcAAD+7qkKycK2qsQBo4Ygx1XV9DvJXOuMTNRHbfAn+4KaZuPKkXt3rLQyxRNEEV+moQdDJhsf3T3VwpWGXjD0BPL7gFHacpdRAAAA"
  },
  "/images/dishes/momo-burger.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoQABQAPxFysFAsJqSisAgBgCIJbACdABuYTuneRufqrsYgAP6oUgYt+TrMdwk+iycVhCOTXfhUSQaLsqLDIOClUg76HEyPsMXWYEsxUhxHn7GzBOJc4Cm4TevAmdV16F1CKmiAAAA="
  },
  "/images/dishes/peri-peri-momo.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQBACdASoQABQAPxFysFAsJqSisAgBgCIJagAAUquvAYZf1Uhdy+L4B/kAAP1oSviJ2W1SVEUXApUfJumX42U7mpAnPy3+z8UClFb9FddMSLv4PQIVBRSjpnsk7cEjw1AAAA=="
  },
  "/images/dishes/royal-chicken-bucket.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoQABQAPxFysFAsJqSisAgBgCIJagCw7ywBDlfun4F9rf1uUAD+v64Ih3EoQg+wSTLGJDoSsA+Csy/+jueZdHPqAZ6PxkFeErHg2wLvcnnDPE3fkfz+uoQZuBLiIEwVk2neqp5y13ELroAA"
  },
  "/images/dishes/steam-momo.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACwAwCdASoQABQAPxFysFAsJqSisAgBgCIJZAAAPF2aW9HAalrNgAD+6R4PANAu7u7AR6unv6dHdnjZXwatsdiPtPZiwLtw8H9p5gLNsyU5lqHklytWOlB5WXMIYjtCzlS1BRhpRho6PJsR7q8ahw927dh9C5MAAAA="
  },
  "/images/dishes/sweet-corn-chaat.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoQABQAPxFwsFAsJiSisAgBgCIJZgAAUz/Uf1ZwasRPnQc4pAD+7EIQGGgu3/W2RZZXnFAF0rx/GZY4EDq+tI3/5syUDVOR/v+9vvwohrDyQhMv76h7aArHRXHppi7GdefaHwCSSREP4AAA"
  },
  "/images/hero/momo-basket.jpg": {
    "width": 1856,
    "height": 2304,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwBACdASoQABQAPxFwsFAsJiSisAgBgCIJZACw7B0+gutLu8tixlSbBEgA/u6hVwqbyrrq8Pg3WC4hsOLTCDr0m03+E+Mf14X8PPzfzR1ZFi4csJ3YuqFOpV4e8IejOWYGZqLYhZypVtAA"
  },
  "/images/hero/video-poster.jpg": {
    "width": 860,
    "height": 1068,
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwBACdASoQABQAPxFysFAsJqSisAgBgCIJZACuHB0+guqCt0AEsd6HrQ4A/u6hVwsdrVum9fKJSFryWWNEyFlPQZrggm24iqn1T7UpStSDcGcWmgl/9KmEjRii5uefsKwIOIcyRWUna764AAA="
  },
  "/images/mood/coffee-pour.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwBACdASoQABQAPxFysFAsJqSisAgBgCIJZQC/OB8nT0M8XMjvE3CqdAAA/u6hURz95YJyNQJtR+CyqcLJK++ON65pcyQNTFc2JSuX0BZ4Tzbu8xIbPHAocIWM2rSY0QAAAA=="
  },
  "/images/mood/kitchen-action.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwBACdASoQABQAPxFwsFAsJiSisAgBgCIJZgC7AB6JyQKSKqnPeY/mEyAA/ro4kF3Mj162BhEcngSi79qsXQcSDsMqMcuXRGm7bVAgTqhMz38SXv4+z5UuU9TXE64CAHiRs0AA"
  },
  "/images/mood/storefront-dusk.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQBACdASoQABQAPxFysFAsJqSisAgBgCIJbACdIIjCriUG2ctPYuOnsAD+oyIzFfyRG7G19aLTfvUGP3jbWjUOmiSmFALHIiHsn/rXglZD9w8toTA+Y/4fJT7TRn2ZkuA/BwAShqxMcexGtuJk5zEYAAA="
  },
  "/images/textures/cheese-pull.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAwCdASoQABQAPxFysFAsJqSisAgBgCIJZAAAW36Bu2j2Ks1o1fyAAP7r7ihsxyhQGThbIBHgWX209aSbVTktwoKCns1A5ESmcxoiViI/e5bgH4JsiHey3OlkSoCqVhEU9Z+aM6DE3bAA"
  },
  "/images/textures/chutney-swirl.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQAwCdASoQABQAPxFysFAsJqSisAgBgCIJZACdAB4T+GX5m1zOVAAA/s2EvyErY3a3wSLe/9UJSg8PqAAiarieOj8Cqv35WecHMOM+x7ZE3+/vK42hdjKOtJR7lC0sNQygNsqlFNmAfdgfQzyTMFL00M8fYRGmWtVOUXgA"
  },
  "/images/textures/fry-crunch.jpg": {
    "width": 928,
    "height": 1152,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAwCdASoQABQAPxFysFAsJqSisAgBgCIJbACw7CDjql42XEknNy5UAP7sO+/tAWbxjFrZKpO8BWuP287siQdCCo4zdcqbsw/paN5PCpR3yHmPPOzie2wsgM+f0r5WSulFCh4wWUQeAAAA"
  }
};
