/**
 * Sharp pipeline (spec §5): public/images/raw/<group>__<name>.(png|jpg|webp)
 *   → public/images/<group>/<name>.jpg   (hero ≤1920w, others ≤1280w, q82)
 *   → data/images.generated.ts           (intrinsic size + 16px blurDataURL)
 *
 * Multi-width AVIF/WebP variants are produced on demand by the next/image
 * optimizer from these JPEG masters, so they are not pre-generated here.
 *
 * Run: node scripts/process-images.mjs
 */
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname, "..");
const RAW = path.join(ROOT, "public", "images", "raw");
const OUT_BASE = path.join(ROOT, "public", "images");
const MANIFEST = path.join(ROOT, "data", "images.generated.ts");

const MAX_WIDTH = { hero: 1920, default: 1280 };
const QUALITY = 82;

const files = (await readdir(RAW).catch(() => [])).filter((f) =>
  /\.(png|jpe?g|webp)$/i.test(f),
);

if (files.length === 0) {
  console.log("No raw images found in public/images/raw — nothing to do.");
  process.exit(0);
}

const entries = {};

for (const file of files) {
  const stem = file.replace(/\.(png|jpe?g|webp)$/i, "");
  const [group, ...rest] = stem.split("__");
  const name = rest.join("__");
  if (!group || !name) {
    console.warn(`Skipping ${file} — expected "<group>__<name>.<ext>"`);
    continue;
  }

  const maxWidth = MAX_WIDTH[group] ?? MAX_WIDTH.default;
  const outDir = path.join(OUT_BASE, group);
  await mkdir(outDir, { recursive: true });
  const outFile = path.join(outDir, `${name}.jpg`);

  const image = sharp(path.join(RAW, file)).rotate();
  const resized = image.resize({ width: maxWidth, withoutEnlargement: true });
  const { width, height } = await resized
    .jpeg({ quality: QUALITY, mozjpeg: true })
    .toFile(outFile);

  const blurBuffer = await sharp(outFile)
    .resize(16, undefined, { fit: "inside" })
    .webp({ quality: 30 })
    .toBuffer();

  const publicPath = `/images/${group}/${name}.jpg`;
  entries[publicPath] = {
    width,
    height,
    blurDataURL: `data:image/webp;base64,${blurBuffer.toString("base64")}`,
  };
  console.log(`✓ ${publicPath} (${width}×${height})`);
}

const banner = `/**
 * AUTO-GENERATED by scripts/process-images.mjs — do not edit by hand.
 * Maps public image paths to intrinsic size + blur placeholder.
 */
export interface GeneratedImage {
  width: number;
  height: number;
  blurDataURL: string;
}

export const generatedImages: Record<string, GeneratedImage> = `;

await writeFile(MANIFEST, banner + JSON.stringify(entries, null, 2) + ";\n");
console.log(`\nWrote ${Object.keys(entries).length} entries to data/images.generated.ts`);
